FROM ruby:2.4.1
MAINTAINER Anthony Ikeda <anthony.ikeda@gmail.com>

RUN apt-get update
RUN apt-get install -y build-essential libssl-dev libreadline-dev zlib1g-dev

VOLUME /ruby-app
COPY ./Gemfile /ruby-app/
COPY ./Gemfile.lock /ruby-app/
# COPY ./app /app
# COPY ./bin /app
# COPY ./config ./app


WORKDIR /ruby-app
RUN gem install bundler
RUN bundle install