# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98510226583610aa4702df4d157de376e9555110e31c130d82d7a6593c481a1d0a397347ee038100a98ac3cbea28c9cd1d78805f45c0b230eca27f244c7a4055

test:
  secret_key_base: 1ebb35b845cc6854c779a857ce2b5c5527a915ec967ea741261c5ea01e8604af823d6f2841c8d329718af7d63963db599d9cc7b768b4687aa574504c80ff5774

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
